### ISSUE TITLE
这个sdk在linux异常！！

### ISSUE THREAD

**Issue by liuyl1992** [aliyun/aliyun-log-dotnetcore-sdk#12]
这个sdk版本在linux 的cetos上异常

System.Net.Http.HttpRequestException: Resource temporarily unavailable ---> System.Net.Sockets.SocketException: Resource temporarily unavailable
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at

**Comment by liuyl1992** [comment]
目前是在centos中和阿里云k8s上都会引发此问题

**Comment by liuyl1992** [comment]
顺便问下大阿里大佬们，这个库后续会改用httpclientFactory改写吗。。。

**Comment by JasonMing** [comment]
> 目前是在centos中和阿里云k8s上都会引发此问题

这个提示感觉是无外网连接导致的？

**Comment by JasonMing** [comment]
> 顺便问下大阿里大佬们，这个库后续会改用httpclientFactory改写吗。。。

HttpClientFactory基于.NetCore2.1，如果升级可能会引起不兼容。

基于这个原因我可能会把网络链接及序列化部分(#10 )的接口单独抽离出来，下面加上几个默认的适配器，如果你们在默认适配器的范围外工作，自己实现一个就可以连。

**Comment by liuyl1992** [comment]
解决了。。。。是阿里云个别容器访问外网失败。。。。

**Comment by liuyl1992** [comment]
解决。。
